#!/bin/bash

WHITE='\033[0m'
GREEN='\033[0;32m'
YELLOW='\033[0;33m'

echo -e "${YELLOW} >> ${WHITE}Ingrese el nombre de dominio para el sitio (ejemplo.com):"
read domain

echo -e "${YELLOW} >> ${WHITE}Ingrese el puerto en el que se ejecutará la API:"
read port

if ! command -v nginx &> /dev/null
then
    echo "Nginx no está instalado. Instalando..."
    sudo apt-get update
    sudo apt-get install nginx -y
fi

CLOUDFLARE_FILE_PATH=/etc/nginx/cloudflare
clear
echo -e "${GREEN}[Iniciando] ${WHITE}Configurando Cloudflare..."
sleep 5
echo -e "${GREEN}[Iniciando] ${WHITE}Eliminando configuración anterior de Cloudflare..."
sudo truncate -s 0 $CLOUDFLARE_FILE_PATH
sleep 5
echo -e  "${GREEN}[Iniciando] ${WHITE}Descargando nueva configuración de Cloudflare..."

echo "#Cloudflare" > $CLOUDFLARE_FILE_PATH;
echo "" >> $CLOUDFLARE_FILE_PATH;

echo "# - IPv4" >> $CLOUDFLARE_FILE_PATH;
for i in `curl -s -L https://www.cloudflare.com/ips-v4`; do
    echo "set_real_ip_from $i;" >> $CLOUDFLARE_FILE_PATH;
done

echo "" >> $CLOUDFLARE_FILE_PATH;
echo "# - IPv6" >> $CLOUDFLARE_FILE_PATH;
for i in `curl -s -L https://www.cloudflare.com/ips-v6`; do
    echo "set_real_ip_from $i;" >> $CLOUDFLARE_FILE_PATH;
done

echo -e "" >> $CLOUDFLARE_FILE_PATH;
echo "real_ip_header CF-Connecting-IP;" >> $CLOUDFLARE_FILE_PATH;
sleep 5
echo -e "${GREEN}[Iniciando] ${WHITE}Configuración de Cloudflare completada."
sleep 5
echo -e "${GREEN}[Iniciando] ${WHITE}Configurando Nginx..."

nginx -t && systemctl reload nginx

echo -e "${GREEN}[Iniciando] ${WHITE}Configurando sitio en Nginx..."
sleep 5

sudo tee /etc/nginx/sites-available/$domain.conf << EOF
server {
	listen 80;
	listen [::]:80;
    server_name $domain;

    include /etc/nginx/cloudflare;
    real_ip_header X-Forwarded-For;

    location / {
        proxy_pass http://127.0.0.1:$port;
 	proxy_http_version 1.1;
        proxy_set_header Upgrade \$http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host \$host;
        proxy_cache_bypass \$http_upgrade;
    }
}
EOF

sudo ln -s /etc/nginx/sites-available/$domain.conf /etc/nginx/sites-enabled/

sudo nginx -t
sudo service nginx restart
echo -e "${GREEN}Zeew Scrips${WHITE} ¡Listo! Se ha configurado el sitio en Nginx para el dominio${YELLOW} $domain ${WHITE}y se ejecutará en el puerto ${YELLOW}$port.${WHITE}"

